# <https://github.com/python-poetry/poetry/discussions/4205#discussioncomment-911983>

name: CI
on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '^3.8'

      - run: curl -sSL https://install.python-poetry.org | python3 - -y

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
          key: |
            r1/${{ github.workflow }}/${{ runner.os }}/poetry/${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            r1/${{ github.workflow }}/${{ runner.os }}/poetry/

      - run: poetry install --no-interaction
      - run: pyright .
      - run: yapf --diff --recursive .
