# <https://github.com/python-poetry/poetry/discussions/4205#discussioncomment-911983>

name: CI
on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "^3.13"

      - run: curl -sSL https://install.python-poetry.org | python3 - -y

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: |
            r1/${{ github.workflow }}/${{ runner.os }}/poetry/${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            r1/${{ github.workflow }}/${{ runner.os }}/poetry/

      - run: poetry install --no-interaction --no-root
      - run: poetry run basedpyright
      - run: poetry run ruff check
      - run: poetry run ruff format --diff
